lesion_config = {
    "model": "deeplab",	# Available options: classic_unet, unet_plus_plus, deeplab
	"data": "lesion",
	"polar_training": False,
	"num_epochs": 50,
	"lr": 1e-03,
	"l2_reg": 0,
	"gpu": 0,
	"num_workers": 8,
	"batch_size": 64,
	"step_size": [30, 60, 90],
	"gamma": 1,
	"crop_size": [256, 256],
	"perc_data": 1,
	"train_val_split": 0.9,
	"seed": 1,
	"loss_func": "multiclass_combined",
	"class_weights": [1, 1],
	"num_classes": 2,
	"augment": ['rot', 'zoom', 'hflip', 'vflip'],
	"verbose_idx": 30,
	"pos_sample_chance": 1,
	"no_standardize": False,
	"wmap_weight": 3,
	"weight_score": [1, 1],
	"Training_ROI_Vicinity": 4,
	"use_weightmaps": True,
	"require_one_hot": True,
	"num_out_classes": 2
}
